FROM python:3.9

RUN pip install dbt-postgres==1.3.1 psycopg2==2.9.3 pytz

ENV POSTGRES_DATABASE=airflow
ENV POSTGRES_HOST=postgres
ENV POSTGRES_PASSWORD=airflow
ENV POSTGRES_PORT=5432
ENV POSTGRES_SCHEMA=dbt_cosmos
ENV POSTGRES_USER=airflow

RUN mkdir /root/.dbt
COPY dags/dbt/jaffle/profiles.yml /root/.dbt/profiles.yml

COPY dags dags
COPY dags/dbt/jaffle/dbt_project.yml dags/dbt/jaffle_shop/dbt_project.yml
