version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    command: postgres -c max_connections=500
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - mynet

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - mynet

  dbt-container:
    tty: true
    image: dbt:latest
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ./dbt:/jaffle_shop
      - ./dbt_realiability:/dbt_realiability
    depends_on:
      - postgres
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  postgres:
  pgadmin:
