FROM python:3.8

RUN apt-get update -y && \
    apt-get install -y \
    telnet \
    iputils-ping \
    python3 \
    python3-pip \
    git \
    vim \
    awscli \
    curl \
    ca-certificates \
    libffi-dev \
    libpq-dev \
    postgresql \
    postgresql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    pip3 install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org \
    dbt-core psycopg2-binary dbt-postgres

ENV DBT_PROFILES_DIR=/home/jaffle_shop
